name: Simple Usage

on: push


jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - run: echo $PATH
      - uses: docker://pandoc/core:2.9
        with:
          args: "readme.md -o readme.pdf" 

